name: floradex
description: "My love letter to a pretty lady."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  envied: ^1.3.2
  http: ^1.6.0
  image_picker: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  envied_generator: ^1.3.2
  build_runner: ^2.10.4

flutter:
  uses-material-design: true

  fonts:
    - family: Zain
      fonts:
        - asset: fonts/Zain-Black.ttf
          weight: 900
        - asset: fonts/Zain-ExtraBold.ttf
          weight: 800
        - asset: fonts/Zain-Bold.ttf
          weight: 700
        - asset: fonts/Zain-Regular.ttf
          weight: 400
        - asset: fonts/Zain-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/Zain-Light.ttf
          weight: 300
        - asset: fonts/Zain-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/Zain-ExtraLight.ttf
          weight: 200